---
title: "binomial"
author: "Abby_Robinson"
date: "11/19/2021"
output: html_document
---
##chi squared approxiamation may be incorrect error: delete the zeros!!

```{r}
library(curl)
library(survival)
library(ggplot2)
library(survminer)
```

```{r}
f <- curl("https://raw.githubusercontent.com/butterfliesrcool/BI588_Replication_Assignment/main/Adelpha2016_binomial.csv")
data  <- read.csv(f, header = TRUE, sep = ",", stringsAsFactors = FALSE)
data
```

```{r}
attacks <- subset(data, attacks >= "1", drop = FALSE)
attacks
table(attacks$attacks, attacks$species)
```

```{r}
model <- survfit(Surv(day, day+1, attacks) ~ species, data=data)
model
summary(model)
```

```{r}
m <- survfit(Surv(day, day+1, attacks) ~ species, data=data)
m
summary(m)
```

```{r}
plot(model, xlab="Time (days)", 
           ylab="Survivorship",
           ylim = c(0.85, 1.0), 
           xlim = c(1, 5))
```

```{r}
library(tayloRswift)
p <- ggsurvplot(fit = model, 
           palette = c("taylorRed"),
           xaxt = "n",
           xlab="Time (days)", 
           ylab="Survivorship",
           ylim = c(0.85, 1.0), 
           xlim = c(1, 5),  
           data = data, 
           axes = FALSE)

p

##rename the x axis values 
p$plot <- p$plot + 
                  scale_x_continuous(breaks = c(1,2,3,4,5),
                                     labels = c(0,1,2,3,4))
p$plot
```

```{r}
library(tayloRswift)
p <- ggsurvplot(fit = model, 
           xaxt = "n",
           xlab="Time (days)", 
           ylab="Survivorship",
           ylim = c(0.85, 1.0), 
           xlim = c(1, 5),  
           data = data, 
           axes = FALSE)

##use Red (Taylor's Version) color palette 
p$plot <- p$plot + scale_color_taylor(palette = "taylorRed")
p$plot <- p$plot + theme_minimal()
p$plot

##rename the x axis values 
p$plot <- p$plot + 
                  scale_x_continuous(breaks = c(1,2,3,4,5),
                                     labels = c(0,1,2,3,4))
p$plot


```