---
title: "Generalized Linear Model"
author: "Abby_Robinson"
date: "11/29/2021"
output: html_document
---
NOTES::
1. subset junonia and replicate the survival analysis comparing day 1 to day 4 
2. the glm i have replicates the results presented in the figure legend
```{r}
library(curl)
library(ggplot2)
library(broom)
library(lmtest)
```

```{r}
f <- curl("https://raw.githubusercontent.com/butterfliesrcool/BI588_Replication_Assignment/main/Adelpha2016.csv")
count.data  <- read.csv(f, header = TRUE, sep = ",", stringsAsFactors = FALSE)
count.data
```

```{r}
name <- c("evarete", "iphiclus", "leucopthalma", "serpa") 
is.character(names)
total.attacks <- c(52, 30, 51, 56) 
attack.rates <- cbind((total.attacks/500)*100)
attack.rates

summary.stats <- data.frame(name, total.attacks, attack.rates)
summary.stats
```

```{r}
f <- curl("https://raw.githubusercontent.com/butterfliesrcool/BI588_Replication_Assignment/main/Adelpha2016_binomial.csv")
data  <- read.csv(f, header = TRUE, sep = ",", stringsAsFactors = FALSE)
data
```

```{r}
prop <- (count.data$attacks)/500

count.data$prop <- prop
count.data
glm <- glm(data = count.data, prop ~ species + day, family = "poisson")
bar <- confint(glm)
bar
```

```{r}
glm <- glm(data = count.data, attacks ~ species + day, family = "poisson")
bar <- confint(glm)
bar

iph <- subset(count.data, species  == "iphiclus", drop = FALSE)
b <- ggplot(glm, aes(x=species, y=attacks)) 
b <- b + geom_bar(stat="identity")
b <- b + geom_text(data = iph, label = "*")
b <- b + theme_minimal()
b <- b + theme_classic()
b
##inserting images into ggplot

library(ggplot2)
library(ggimage)
library(dplyr)

set.seed(1234)



df = data.frame(
  group = c('evarete', 'iphiclus', 'leucopthalma', 'serpa'),
  value = 1:4,
  image = sample(img, size=3, replace = TRUE)
) %>% 
  mutate(value1 = .5 * value)

ggplot(df, aes(group, value)) + 
  geom_col() + 
  geom_image(aes(image=image, y = value1), size=.2)

 ##extra code 
b <- b + geom_signif(comparisons = list(c("evarete", "iphiclus")), map_signif_level=TRUE)
b
```

```{r}
glm <- glm(data = summary.stats, attack.rates ~ names, family = "poisson")

m <- lm(data = binomial.data, attacks ~ species)
summary(m)

library(dplyr)
library(car)
m3 <- aov(count.data$attacks ~ count.data$species)
posthoc <- TukeyHSD(m3, "count.data$species", conf.level = 0.95)
posthoc 
```

##we are using the poisson distribution here so we use the count data 
```{r}
glm <- glm(data = count.data, attacks ~ species + day, family = "poisson")
summary(glm)
confint(glm)

anova(glm)

barplot(glm)
```

```{r}
glm1 <- glm(data = count.data, attacks ~ 1, family = "poisson")
glm2 <- glm(data = count.data, attacks ~ species, family = "poisson")
glm3 <- glm(data = count.data, attacks ~ species + day, family = "poisson")
glm4 <- glm(data = count.data, attacks ~ day, family = "poisson")

# using the anova function
anova(glm1, glm2, glm3, glm4,  test = "Chisq")
```

```{r}
library(lme4)
model <- glmer(attacks ~ species + day + (1|site), family=poisson, data = count.data)
summary(model)
```

####Sources
http://www.sthda.com/english/wiki/ggplot2-themes-and-background-colors-the-3-elements

https://www.geeksforgeeks.org/change-color-of-bars-in-barchart-using-ggplot2-in-r/
http://sape.inf.usi.ch/quick-reference/ggplot2/colour

https://www.delftstack.com/howto/r/scale_y_continuous-in-r/

https://stackoverflow.com/questions/25061822/ggplot-geom-text-font-size-control/25062509